TR-66: [WtYuMpUw]: added optional parameter to set-payment-method.js,…
globalpayments/ecommerce-magento-2 pull request #22
Opened 2020-11-06 08:38 UTC by ahumulescu

… so a user can extend it and add extension attributes to the paymentData object

2020-11-06 15:03 UTC, slogsdon requested changes

2020-11-06 15:03 UTC, slogsdon commented on RealexPayments/HPP/view/frontend/web/js/action/set-payment-method.js
> +                    paymentData['extension_attributes'][currentAttribute['code']] = currentAttribute['value'];
I'd simplify this line to:

```js
paymentData.extension_attributes[currentAttribute.code] = currentAttribute.value;
```

2020-11-18 14:32 UTC, ahumulescu commented on RealexPayments/HPP/view/frontend/web/js/action/set-payment-method.js
> +                    paymentData['extension_attributes'][currentAttribute['code']] = currentAttribute['value'];
I've simplified it

2020-11-18 14:46 UTC, securesubmit-buildmaster approved these changes

2020-11-18 14:47 UTC, slogsdon approved these changes

2020-11-18 14:50 UTC, merged